name: Workflow con Passaggio Valori (PowerShell)

on:
  workflow_dispatch: # Permette di avviare il workflow manualmente

jobs:
  build:
    runs-on: windows-latest # Specifica il sistema operativo Windows

    steps:
    - name: Step 1 - Genera un valore con PowerShell
      id: step1_generazione # Assegna un ID a questo step per referenziarlo
      shell: pwsh # Specifica che useremo PowerShell
      run: |
        # Questo è un esempio: puoi generare qualsiasi valore tu voglia
        $ValoreGenerato = "Ciao da Step 1 su Windows!"
        Write-Host "Valore generato: $ValoreGenerato"

        # Imposta l'output dello step. La sintassi per PowerShell è `echo "::set-output name=nome_output::valore"`
        # Nota: in GitHub Actions le variabili d'ambiente come GITHUB_OUTPUT non funzionano direttamente come in bash per gli output.
        # Devi usare il comando 'echo "::set-output ..."' per retrocompatibilità o la variabile GITHUB_OUTPUT su versioni di runner più recenti.
        # Per massima compatibilità e chiarezza, usiamo la sintassi raccomandata per gli output di step.
        # Aggiornamento: dalla fine del 2022, è preferibile usare GITHUB_OUTPUT anche in PowerShell, come mostrato qui sotto.
        # Assicurati che il runner sia aggiornato.
        echo "valore_output=$ValoreGenerato" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        Write-Host "Output 'valore_output' impostato."

    - name: Step 2 - Usa il valore dallo Step 1 con PowerShell
      shell: pwsh # Specifica che useremo PowerShell
      run: |
        # Accedi al valore usando l'ID dello step e il nome dell'output
        # La sintassi per accedere agli output è la stessa in qualsiasi shell
        $ValoreDaStep1 = "${{ steps.step1_generazione.outputs.valore_output }}"
        Write-Host "Il valore ricevuto dallo Step 1 è: $ValoreDaStep1"

        # Puoi ora usare questo valore per qualsiasi operazione nello Step 2
        # Ad esempio, creare un file, passarlo a un altro comando, ecc.
        Set-Content -Path "output_step2.txt" -Value $ValoreDaStep1
        Write-Host "File 'output_step2.txt' creato con il valore."
